{
 "title": "parking-recorder",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average storage latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(parking_recorder_storage_latency_seconds_sum[$__rate_interval]) /\nrate(parking_recorder_storage_latency_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average processing latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(parking_recorder_processing_latency_seconds_sum[$__rate_interval]) /\nrate(parking_recorder_processing_latency_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average queuing latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(parking_recorder_queueing_latency_seconds_sum[$__rate_interval]) /\nrate(parking_recorder_queueing_latency_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}